#!/bin/bash

### BEGIN INIT INFO
# Provides:          anonsurf
# Required-Start:
# Required-Stop:
# Should-Start:
# Default-Start:
# Default-Stop:
# Short-Description: Transparent Proxy through TOR.
### END INIT INFO

# AnonSurf is inspired by the homonimous module of PenMode, developed by the "Pirates' Crew" in
# order to make it fully compatible with
# Parrot  OS and other debian-based systems, and it is part of
# parrot-anon package.
#
#
# Devs:
# Lorenzo 'EclipseSpark' Faletra <eclipse@frozenbox.org>
# Lisetta 'Sheireen' Ferrero <sheireen@frozenbox.org>
# Francesco 'mibofra'/'Eli Aran'/'SimpleSmibs' Bonanno <mibofra@ircforce.tk> <mibofra@frozenbox.org>
#
#
# anonsurf is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# You can get a copy of the license at www.gnu.org/licenses
#
# anonsurf is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Parrot Security OS. If not, see <http://www.gnu.org/licenses/>.


export WHITE='\033[1;97m'
export CYAN='\033[1;96m'
export BLUE='\033[1;94m'
export GREEN='\033[1;92m'
export RED='\033[1;91m'
export RESETCOLOR='\033[1;00m'

# Destinations you don't want routed through Tor
TOR_EXCLUDE="192.168.0.0/16 172.16.0.0/12 10.0.0.0/8"

# The UID Tor runs as
# change it if, starting tor, the command 'ps -e | grep tor' returns a different UID
TOR_UID="debian-tor"

# Tor's TransPort
TOR_PORT="9040"

# Is resolvconf installed?
if [[ ! -z `dpkg -l |grep resolvconf` ]]; then 
	resolvconf_support=true;
else
	resolvconf_support=false;
fi


function init {
	echo -e -n " $GREEN*$BLUE killing dangerous applications$RESETCOLOR\n"
	killall -q chrome dropbox iceweasel skype icedove thunderbird firefox chromium xchat transmission deluge pidgin pidgin.orig
	
	echo -e -n " $GREEN*$BLUE cleaning some dangerous cache elements"
	bleachbit -c adobe_reader.cache chromium.cache chromium.current_session chromium.history elinks.history emesene.cache epiphany.cache firefox.url_history flash.cache flash.cookies google_chrome.cache google_chrome.history  links2.history opera.cache opera.search_history opera.url_history &> /dev/null
}


function starti2p {
	echo -e -n " $GREEN*$BLUE starting I2P services$RESETCOLOR\n"
	service tor stop

	# Modify DNS settings
	if [ "$resolvconf_support" = false ] 
	then
		cp /etc/resolv.conf /etc/resolv.conf.bak;
		touch /etc/resolv.conf;
		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' > /etc/resolv.conf;
		echo -e " $GREEN*$BLUE Modified resolv.conf to use localhost and Private Internet Access DNS$RESETCOLOR\n";
	else
		cp /etc/resolvconf/resolv.conf.d/head{,.bak};
		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' >> /etc/resolvconf/resolv.conf.d/head;
		echo -e " $GREEN*$BLUE Modified resolvconf to use localhost and Private Internet Access DNS$RESETCOLOR\n";
		resolvconf -u;
	fi
	sudo -u i2psvc i2prouter start
	sleep 2
	xdg-open 'http://127.0.0.1:7657/home'
}

function stopi2p {
	echo -e -n " $GREEN*$BLUE stopping I2P services\n$RESETCOLOR"
	sudo -u i2psvc i2prouter stop
	
	# restore DNS settings
	if [ "$resolvconf_support" = false ] 
	then
		if [ -e /etc/resolv.conf.bak ]; then
			rm /etc/resolv.conf
			cp /etc/resolv.conf.bak /etc/resolv.conf
		fi
	else
		mv /etc/resolvconf/resolv.conf.d/head{.bak,}
		resolvconf -u
	fi
}


function ip {

	echo -e $BLUE"\nMy public ip:"$RESETCOLOR
	sleep 1
	curl -s -m 10 ipinfo.io| tr -d '"{}' | sed 's/ //g'
}

ip_menu="$(curl -s -m 10 ipinfo.io/ip)" 
co_menu="$(curl -s -m 10 ipinfo.io/country)"

function start {
	# Make sure only root can run this script
	if [ $(id -u) -ne 0 ]; then
		echo -e -e "\n$GREEN[$RED!$GREEN] $RED You aren't a root bitch!$RESETCOLOR\n" >&2
		exit 1
	fi
	
	# Check defaults for Tor
	grep -q -x 'RUN_DAEMON="yes"' /etc/default/tor
	if [ $? -ne 0 ]; then
		echo -e "\n$GREEN[$RED!$GREEN]$RED Please add the following to your /etc/default/tor and restart service:$RESETCOLOR\n" >&2
		echo -e "$BLUE#----------------------------------------------------------------------#$RESETCOLOR"
		echo -e 'RUN_DAEMON="yes"'
		echo -e "$BLUE#----------------------------------------------------------------------#$RESETCOLOR\n"
		exit 1
	fi	
	
	# Kill IPv6 services
	echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Stopping IPv6 services:$RESETCOLOR\n"
	sed -i '/^.*\#kali-anonsurf$/d' /etc/sysctl.conf #delete lines containing #kali-anonsurf in /etc/sysctl.conf
	# add lines to sysctl.conf that will kill ipv6 services
	echo "net.ipv6.conf.all.disable_ipv6 = 1 #kali-anonsurf" >> /etc/sysctl.conf
	echo "net.ipv6.conf.default.disable_ipv6=1 #kali-anonsurf" >> /etc/sysctl.conf
	sysctl -p > /dev/null  # have sysctl reread /etc/sysctl.conf

	echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Starting anonymous mode:$RESETCOLOR\n"
	
	if [ ! -e /var/run/tor/tor.pid ]; then
		echo -e " $RED*$BLUE Tor is not running! $GREEN starting it $BLUE for you$RESETCOLOR\n" >&2
		service network-manager force-reload > /dev/null 2>&1
		killall dnsmasq > /dev/null 2>&1
		killall nscd > /dev/null 2>&1	
		service tor start
		sleep 1
	fi
	if ! [ -f /etc/network/iptables.rules ]; then
		iptables-save > /etc/network/iptables.rules
		echo -e " $GREEN*$BLUE Saved iptables rules$RESETCOLOR\n"
	fi
	
	iptables -F
	iptables -t nat -F
	
	if [ "$resolvconf_support" = false ] 
	then
		cp /etc/resolv.conf /etc/resolv.conf.bak
		touch /etc/resolv.conf
		echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' > /etc/resolv.conf
		echo -e " $GREEN*$BLUE Modified resolv.conf to use Tor and Private Internet Access DNS"
	else
		cp /etc/resolvconf/resolv.conf.d/head{,.bak}
                echo -e 'nameserver 127.0.0.1\nnameserver 209.222.18.222\nnameserver 209.222.18.218' >> /etc/resolvconf/resolv.conf.d/head
                echo -e " $GREEN*$BLUE Modified resolvconf to use localhost and Private Internet Access DNS$RESETCOLOR\n"
                resolvconf -u
	fi

	# set iptables nat
	iptables -t nat -A OUTPUT -m owner --uid-owner $TOR_UID -j RETURN
	iptables -t nat -A OUTPUT -p udp --dport 53 -j REDIRECT --to-ports 53
	iptables -t nat -A OUTPUT -p tcp --dport 53 -j REDIRECT --to-ports 53
	iptables -t nat -A OUTPUT -p udp -m owner --uid-owner $TOR_UID -m udp --dport 53 -j REDIRECT --to-ports 53
	
	#resolve .onion domains mapping 10.192.0.0/10 address space
	iptables -t nat -A OUTPUT -p tcp -d 10.192.0.0/10 -j REDIRECT --to-ports 9040
	iptables -t nat -A OUTPUT -p udp -d 10.192.0.0/10 -j REDIRECT --to-ports 9040
	
	#exclude local addresses
	for NET in $TOR_EXCLUDE 127.0.0.0/9 127.128.0.0/10; do
		iptables -t nat -A OUTPUT -d $NET -j RETURN
	done
	
	#redirect all other output through TOR
	iptables -t nat -A OUTPUT -p tcp --syn -j REDIRECT --to-ports $TOR_PORT
	iptables -t nat -A OUTPUT -p udp -j REDIRECT --to-ports $TOR_PORT
	iptables -t nat -A OUTPUT -p icmp -j REDIRECT --to-ports $TOR_PORT
	
	#accept already established connections
	iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
	
	#exclude local addresses
	for NET in $TOR_EXCLUDE 127.0.0.0/8; do
		iptables -A OUTPUT -d $NET -j ACCEPT
	done
	
	#allow only tor output
	iptables -A OUTPUT -m owner --uid-owner $TOR_UID -j ACCEPT
	iptables -A OUTPUT -j REJECT

	echo -e "$GREEN *$BLUE All traffic was redirected through Tor$RESETCOLOR\n"
	echo -e "$GREEN[$BLUE i$GREEN ]$BLUE You are under AnonSurf tunnel$RESETCOLOR\n"
}





function stop {
	# Make sure only root can run our script
	if [ $(id -u) -ne 0 ]; then
		echo -e "\n$GREEN[$RED!$GREEN] $RED This script must be run as root$RESETCOLOR\n" >&2
		exit 1
	fi
	echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Stopping anonymous mode:$RESETCOLOR\n"

	iptables -F
	iptables -t nat -F
	echo -e " $GREEN*$BLUE Deleted all iptables rules\n$RESETCOLOR"
	
	if [ -f /etc/network/iptables.rules ]; then
		iptables-restore < /etc/network/iptables.rules
		rm /etc/network/iptables.rules
		echo -e " $GREEN*$BLUE Iptables rules restored"
	fi
	
	# restore DNS settings
	if [ "$resolvconf_support" = false ] 
	then
		if [ -e /etc/resolv.conf.bak ]; then
			rm /etc/resolv.conf
			cp /etc/resolv.conf.bak /etc/resolv.conf
		fi
	else
		mv /etc/resolvconf/resolv.conf.d/head{.bak,}
		resolvconf -u
	fi
	
	service tor stop
	
	echo -e "\n$GREEN[$BLUE i$GREEN ]$BLUE Reenabling IPv6 services:$RESETCOLOR\n"

	# reenable IPv6 services
	sed -i '/^.*\#kali-anonsurf$/d' /etc/sysctl.conf #delete lines containing #kali-anonsurf in /etc/sysctl.conf
	sysctl -p # have sysctl reread /etc/sysctl.conf

	service network-manager force-reload > /dev/null 2>&1
	service nscd start > /dev/null 2>&1
	service dnsmasq start > /dev/null 2>&1
	
	echo -e " $GREEN*$BLUE Anonymous mode stopped$RESETCOLOR\n"
}

function change {
	service tor reload
	sleep 2
	echo -e " $GREEN*$BLUE Tor daemon reloaded and forced to change nodes$RESETCOLOR\n"
}

function status {
	service tor status
}

function mymac {
    echo -e $BLUE""MAC Addresses:$RESETCOLOR
    sudo ip l| gawk '{print $2}'
    
}

function mac {
    read -p "Input interface name:" name
    sudo ip link set dev $name down
    sleep 1
    read -p "Reset to original, permanent hardware MAC/Set random vendor MAC of any kind (p/n) :" s
    case $s in
    p)sudo macchanger -p $name;;
    n)sudo macchanger -A $name;;
    *)echo -e "\n$GREEN[$RED!$GREEN] $RED Incorrect value.$RESETCOLOR\n" >&2;exit 1;;
    esac
    sleep 2
    sudo ip link set dev $name up 
    sleep 2
    sudo service networking restart
    echo ""
}

case "$1" in
	start)
		init
		start
	;;
	stop)
		init
		stop
	;;
	change)
		change
	;;
	status)
		status
	;;
	myip|ip)
		ip
	;;
	starti2p)
		starti2p
	;;
	stopi2p)
		stopi2p
	;;
	restart)
		$0 stop
		sleep 1
		$0 start
	;;
    hidemac)
        mac
    ;;
    mymac)
        mymac
    ;;
   *)
echo -e "
$BLUE             ──=Parrot OS AnonSurf Mod=──

       $CYAN┌──[$CYAN$USER$BLUE@$GREY`hostname`$CYAN]─[$BLUE$PWD$CYAN]─[$BLUE$PWD$CYAN]─[$BLUE$ip_menu $co_menu$CYAN]
       $CYAN└──╼\$$WHITE""anonsurf $CYAN{$WHITE""start$CYAN|$WHITE""stop$CYAN|$WHITE""restart$CYAN|$WHITE""change$CYAN""$CYAN|$WHITE""status$CYAN|$WHITE""myip$CYAN|$WHITE""mymac$CYAN|$WHITE""hidemac$CYAN""}
    
       $CYAN start$BLUE ───$WHITE Start system-wide anonymous tunneling under          
                  TOR proxy through iptables.	  
       $CYAN stop$BLUE ────$WHITE Reset original iptables settings and return 
                  to clear navigation
       $CYAN restart$BLUE ─$WHITE Combines \"stop\" and \"start\" options
       $CYAN change$BLUE ──$WHITE Changes identity restarting TOR
       $CYAN status$BLUE ──$WHITE Check if AnonSurf is working properly
       $CYAN myip$BLUE ────$WHITE Show your current IP address
       $CYAN mymac$BLUE ───$WHITE Show your MAC's
       $CYAN hidemac$BLUE ─$WHITE Change MAC address

	  $BLUE ----[ I2P related features ]----

       $CYAN starti2p$BLUE-$WHITE Start i2p services
       $CYAN stopi2p$BLUE ─$WHITE Stop i2p services
$RESETCOLOR
$BLUE    Dance like no one's wathing. Encrypt like everyone is :)
$RESETCOLOR
" >&2
exit 1
;;
esac

echo -e $RESETCOLOR
exit 0
